using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using FlaxEngine;

namespace Game;
public static class Export
{
    public static float UnitScale = 1;
    public static void ExportFP()
    {
        if (string.IsNullOrEmpty(Shared.ProjectPath))
            return;
        var chunks = Terrain.Instance.GetChunksWithObjects();

        StringBuilder sb = new StringBuilder();

        //build lua
#if FLAX_EDITOR
        sb.AppendLine();
#endif
        sb.AppendLine("----------------------------------------------------------");
        sb.AppendLine("--Auto Generated by BAR_Editor");
        sb.AppendLine();
        sb.AppendLine("local setcfg = ");
        sb.AppendLine("{");
        sb.AppendLine("\tunitlist =");
        sb.AppendLine("\t{");
        sb.AppendLine("\t},");
        sb.AppendLine("\tbuildinglist =");
        sb.AppendLine("\t{");
        sb.AppendLine("\t},");
        sb.AppendLine("\tobjectlist =");
        sb.AppendLine("\t{");
        for (int i = 0; i < chunks.Count; i++)
        {
            for (int j = 0; j < chunks[i].objects.Count; j++)
            {
                var chunk = chunks[i];
                var obj = chunk.objects[j];
                //{ name = "Name", x = 0, z = 0, rot = 15975 },

                sb.Append("\t\t");
                sb.Append("{ name = \"");
                sb.Append(obj.Actor.Name);

                sb.Append("\", x = ");

                var x = (obj.Actor.Position.X * UnitScale) * 1000;
                x = (Mathf.Round(x) / 1000);
                sb.Append(x.ToString().Replace(",", "."));
                sb.Append(", z = ");

                var z = (obj.Actor.Position.Z * UnitScale) * 1000;
                z = (Mathf.Round(z) / 1000);
                sb.Append(z.ToString().Replace(",", "."));

                sb.Append(", rot =");
                sb.Append((int)obj.Actor.EulerAngles.Y);
                sb.Append("},");
                sb.AppendLine();
            }
        }
        sb.AppendLine("\n\t}");
        sb.AppendLine("}");
        sb.AppendLine("return setcfg");

#if FLAX_EDITOR
        Debug.Log(sb.ToString());
#endif
        var outdir = Path.Join(Shared.ProjectPath, "mapconfig", "featureplacer");
        if(!Directory.Exists(outdir))
            Directory.CreateDirectory(outdir);
        var stream = File.CreateText(Path.Join(outdir, "set.lua"));
        stream.Write(sb);
        stream.Close();
    }
}